### ISSUE TITLE
Creating translating objects for non-persisted collection elements fails

### ISSUE THREAD

**Issue by szymach** [fsi-open/doctrine-extensions-bundle#61]
If you create an object belonging to a collection and do not persist it manually before flushing (you have cascade persist option set to true), the translation will not be created. This happens because the new object is scheduled for insertion after the relevant method of [translatable listener](https://github.com/fsi-open/doctrine-extensions/blob/master/lib/FSi/DoctrineExtensions/Translatable/TranslatableListener.php#L168) is called.

I am not sure if this is something the bundle should take care of, but perhaps it is a good idea to look into it, since it is kind of troublesome to figure out why translations are not added.

**Comment by JarekW** [comment]
`preFlush` is called before change-set computation, `onFlush` is after computation and before any change, maybe thats the solution

**Comment by szymach** [comment]
Perhaps it is as simple as setting a lower priority on the translatable listener?

**Comment by szymach** [comment]
Moved to [#76](https://github.com/fsi-open/doctrine-extensions/issues/76)
